name: build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Theos
        uses: waruhachi/theos-action@v2.4.6
        with:
          theos-src: 'roothide/theos'
          theos-branch: 'master'
          sdks-src: 'theos/sdks'
          sdks-branch: 'master'
          libgcuniversal: false
          altlist: false

      - name: Build VCamUSB (rootless-Test)
        working-directory: tweak
        run: |
          make clean package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless

      - name: Build dlopen_test (arm64)
        working-directory: server
        run: |
          export THEOS=$HOME/theos
          xcrun -sdk iphoneos clang -arch arm64 -isysroot $(xcrun -sdk iphoneos --show-sdk-path) -o dlopen_test dlopen_test.c
          ldid -S dlopen_test

      - name: Upload .deb
        uses: actions/upload-artifact@v4
        with:
          name: VCamUSB-deb
          path: |
            tweak/packages/*.deb
            server/dlopen_test
